@echo off
chcp 65001 > nul 
echo [INFO] Entrando na pasta frontend...
cd frontend || (echo [ERRO] A pasta 'frontend' não foi encontrada! & pause & exit)

echo [INFO] Verificando ambiente virtual...
IF NOT EXIST "..\venv" (
    echo [INFO] Ambiente virtual não encontrado. Criando...
    python -m venv ..\venv || (echo [ERRO] Falha ao criar o ambiente virtual! & pause & exit)
    echo [INFO] Ativando ambiente virtual...
    call ..\venv\Scripts\activate.bat || (echo [ERRO] Falha ao ativar o ambiente virtual! & pause & exit)
    echo [INFO] Instalando dependências Python...
    pip install -r ..\backend\requirements.txt || (echo [ERRO] Falha ao instalar dependências Python! & pause & exit)
) ELSE (
    echo [INFO] Ambiente virtual já existe. Pulando criação...
    call ..\venv\Scripts\activate.bat || (echo [ERRO] Falha ao ativar o ambiente virtual! & pause & exit)
    echo [INFO] Atualizando dependências Python...
    pip install -r ..\backend\requirements.txt || (echo [ERRO] Falha ao atulizar dependências Python! & pause & exit)
)

timeout /t 1 > nul
echo [INFO] Verificando dependências do npm...
IF NOT EXIST "node_modules" (
    echo [INFO] Dependências do npm não encontradas. Instalando...
    npm install || (echo [ERRO] Falha ao instalar dependências do npm! & pause & exit)
) ELSE (
    echo [INFO] Dependências do npm já instaladas. Pulando instalação...
)

timeout /t 1 > nul
echo [INFO] Iniciando React e Flask...
npm start || (echo [ERRO] O comando 'npm start' falhou! Verifique erros no frontend ou backend. & pause & exit)

pause
